{"uid":"3fdd81cc8bf05847","name":"test_CredKart_Login_params_003[getDataforLogin0]","fullName":"test_case7.Test_CredKart_Login_params#test_CredKart_Login_params_003","historyId":"9959a2ca01d107f91e6e00a3a1820828","time":{"start":1690968142535,"stop":1690968145367,"duration":2832},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1690968138646,"stop":1690968142535,"duration":3889},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"hasContent":false},{"name":"getDataforLogin","time":{"start":1690968142535,"stop":1690968142535,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"stepsCount":0,"hasContent":false}],"afterStages":[],"labels":[{"name":"suite","value":"test_case7"},{"name":"subSuite","value":"Test_CredKart_Login_params"},{"name":"host","value":"DESKTOP-3829VRB"},{"name":"thread","value":"8436-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case7"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"getDataforLogin","value":"('Credencetest@test.com', 'Credence@123')"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"f218a77461e7e4be","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unsuccessful command executed: C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nerror sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115): error trying to connect: dns error: No such host is known. (os error 11001)\n; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1690967726380,"stop":1690967726380,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"47b5696a264db55c","reportUrl":"http://localhost:8080/job/Two_Augest/9/allure/#testresult/47b5696a264db55c","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unsuccessful command executed: C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nerror sending request for url (https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115): error trying to connect: dns error: No such host is known. (os error 11001)\n; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1690967726380,"stop":1690967726380,"duration":0}}]},"tags":[]},"source":"3fdd81cc8bf05847.json","parameterValues":["('Credencetest@test.com', 'Credence@123')"]}